language:
  python

python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO_VERSION=Django==1.6.2
  - DJANGO_VERSION=Django==1.7

install:
  - pip install $DJANGO_VERSION
  - pip install -r test_project/requirements.txt

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
#  - "sh -e install_OS_test_dependencies.sh"
  - "export PATH=`pwd`:$PATH"

script:
  - python manage.py test

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=https://www.djangoproject.com/download/1.7b1/tarball/