language:
  python

python:
  - "2.7"
  - "3.3"

env:
  - DJANGO_VERSION=Django==1.6
  - DJANGO_VERSION=Django==1.7

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "sh -e install_OS_test_dependencies.sh"
  - "export PATH=`pwd`:$PATH"

install:
  - pip install $DJANGO_VERSION
  - pip install -r test_project/requirements.txt

script:
  - cd test_project
  - python manage.py test
